def convert_to_html_template(state: dict) -> dict:
    try:
        content = state.get("node_result") or state.get("node_input")
        
        html_template = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Summary Report</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">Summary Report</h1>
    <div style="background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;">
        <p style="margin: 0;">{content}</p>
    </div>
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
    <p style="font-size: 12px; color: #666; text-align: center;">Generated by Workflow System</p>
</body>
</html>"""
        
        state["node_result"] = html_template
    except Exception as e:
        state["node_result"] = "<p>Error generating HTML template</p>"
    return state 